query searchForUser($search: String!) {
  searchForUser(text: $search) {
    name
    email
    image
    _id
  }
}
mutation AddContact($addContactId: ID!) {
  addContact(id: $addContactId) {
    _id
    members {
      member {
        name
        image
      }
    }
    group
  }
}
query getChats {
  getChats {
    _id
    group
    name
    image
    members {
      member {
        name
        image
        _id
      }
      lastActive
    }
    lastMessage {
      _id
      sendFrom {
        name
        _id
        image
      }
      createdAt
      body {
        text
      }
    }
  }
}
query GetMessages($chatId: ID!, $cursor: Int) {
  getMessages(id: $chatId, cursor: $cursor) {
    _id
    body {
      text
      msg
    }
    sendFrom {
      _id
      image
      name
    }
    createdAt
  }
}
query GetCurrentChat($chatId: ID!) {
  getCurrentChat(chatId: $chatId) {
    _id
    group
    name
    image
    approved
    members {
      member {
        _id
        name
        image
      }
      lastActive
    }
  }
}
