import type { NextPage } from "next";
import Head from "next/head";

const Layout: NextPage = ({ children }) => {
  return (
    <>
      <Head>
        <title>ChatGen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-blackgreen min-h-[100vh]">{children}</main>
    </>
  );
};

export default Layout;
