query searchForUser($search: String!) {
  searchForUser(text: $search) {
    name
    email
    image
    _id
  }
}
mutation AddContact($addContactId: ID!) {
  addContact(id: $addContactId) {
    _id
    members {
      member {
        name
        image
      }
    }
    group
  }
}
query getChats {
  getChats {
    _id
    group
    name
    image
    members {
      member {
        name
        image
        _id
      }
      lastActive
    }
    lastMessage {
      _id
      sendFrom {
        name
        _id
        image
      }
      body {
        text
      }
    }
  }
}
query GetMessages($chatId: ID!) {
  getMessages(id: $chatId) {
    messages {
      _id
      body {
        text
      }
      sendFrom {
        _id
        image
        name
      }
      createdAt
    }
    chat {
      _id
      group
      name
      image
      members {
        member {
          _id
          name
          image
        }
        lastActive
      }
    }
  }
}
mutation SendMessage($body: messageBodyInput, $chatId: ID) {
  sendMessage(body: $body, chatId: $chatId) {
    _id
    body {
      text
    }
    chat {
      _id
    }
    sendFrom {
      name
      image
      _id
    }
  }
}

mutation LastActive($chatId: ID!) {
  lastActive(chatId: $chatId)
}

subscription NewMessage {
  newMessage {
    _id
    sendFrom {
      _id
      name
      image
    }
    body {
      text
    }
    chat {
      _id
    }
  }
}
subscription NewChat {
  newChat {
    _id
    members {
      member {
        name
        image
      }
      lastActive
    }
    group
    name
    image
    lastMessage {
      body {
        text
      }
    }
  }
}
subscription MemberActiveInChat($chatId: ID!) {
  nowActiveInChat(chatId: $chatId) {
    userId
    active
  }  
}

# https://www.youtube.com/watch?v=PYDGjTufGsk&ab_channel=JamieBarton
